services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  catalog:
    image: heathroru/catalog:latest
    build:
      context: .
      dockerfile: src/CatalogService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__PostgresDb=Server=postgres:5432;User Id=postgres;Password=postgres;Database=catalog
      - IdentityServiceUrl=http://identity
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search:
    image: heathroru/search:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDb=mongodb://mongo:mongo@mongo
    ports:
      - 7002:80
    depends_on:
      - mongo
      - rabbitmq
  identity:
    image: heathroru/identity:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostgresDb=Server=postgres:5432;User Id=postgres;Password=postgres;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway:
    image: heathroru/gateway:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80